### ISSUE TITLE
Support extensions other than .glsl

### ISSUE THREAD

**Issue by attilahorvath** [vwochnik/rollup-plugin-glsl#1]
Hi,

Is there any particular reason why this plugin only accepts files with `.glsl` extension?

I'm more used to working with `.vert`/`.frag` for my shaders (as those seem to be preferred by the official Khronos tools), while some other people prefer `.vs`/`.fs` or many other options ([see here for example](https://stackoverflow.com/questions/6432838/what-is-the-correct-file-extension-for-glsl-shaders)).

I'm thinking about opening a pull request to whitelist at least these extensions but I'm just wondering whether this plugin should care about extensions in the first place or just allow any file to be processed (based on the `include` option). What are your thoughts on this?

**Comment by vwochnik** [comment]
You are right. I did this to not have to write an `include` configuration in my project. I have accepted your PR.
